### ISSUE TITLE
aws_access_id deprecation

### ISSUE THREAD

**Issue by johncblandii** [refile/refile-s3#14]
You can see in the [AWS::CredentialProvider docs](http://docs.aws.amazon.com/sdkforruby/api/Aws/CredentialProvider.html) the use of `access_key_id` is deprecated and being removed in the next dot release.

Location of the warning: https://github.com/refile/refile-s3/blob/master/lib/refile/s3.rb#L43-L54.

From Gemfile.lock:

```
    aws-sdk (2.1.23)
      aws-sdk-resources (= 2.1.23)
    aws-sdk-core (2.1.23)
      jmespath (~> 1.0)
    aws-sdk-resources (2.1.23)
      aws-sdk-core (= 2.1.23)
...
    refile (0.6.1)
      mime-types
      rest-client (~> 1.8)
      sinatra (~> 1.4.5)
    refile-mini_magick (0.2.0)
      mini_magick (~> 4.0)
      refile (~> 0.5)
    refile-s3 (0.2.0)
      aws-sdk (~> 2.0)
      refile (~> 0.6.0)
```

From `rails c`:

```
DEPRECATION WARNING: called deprecated method `access_key_id' of an Aws::CredentialProvider, use #credentials instead
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/refile-s3-0.2.0/lib/refile/s3.rb:48:in `initialize'
/srv/www/kast_app/releases/20151017150030/config/initializers/refile.rb:10:in `new'
/srv/www/kast_app/releases/20151017150030/config/initializers/refile.rb:10:in `<top (required)>'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:651:in `load_config_initializer'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `each'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.2.0/tsort.rb:413:in `call'
/usr/local/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/srv/www/kast_app/releases/20151017150030/config/environment.rb:5:in `<top (required)>'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:67:in `console'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/deploy/.bundler/kast_app/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by partydrone** [comment]
I also started noticing this deprecation warning in my logs.

**Comment by PlugIN73** [comment]
solution here #18
