### ISSUE TITLE
TypeError: 0 is not a symbol nor a string

### ISSUE THREAD

**Issue by marr** [refile/refile-s3#16]
Hi,
I am trying to use the refile/s3 gem and having some trouble during the upload. I have a test here in `pictures_controller_test.rb` https://github.com/marr/localpic2

The stacktrace doesn't show much more than this:

```
Api::V1::PicturesControllerTest#test_should_post_create:
TypeError: 0 is not a symbol nor a string
    app/controllers/api/v1/pictures_controller.rb:22:in `create'
    test/controllers/api/v1/pictures_controller_test.rb:17:in `block in <class:PicturesControllerTest>'
```

Any help would be appreciated, cc @hiromipaw

**Comment by marr** [comment]
requiring `aws-sdk-v1` alongside the newer `aws-sdk` was the issue here. I removed the reference to `aws-sdk-v1` which fixed it: https://github.com/marr/localpic2/commit/c6b590c3bdf1bb374081bc42d86968c77cbfd3c4
